--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Lasswell2569149/Joshua
branches: main/heal/PluginBase
projects: [Das plugin ist dafür da das man mit /heal auf volle herzen gehalt wierd]
