name:
main: 
api: 1.0.0
commands:
  info:
    description:Info Befehl
    usage: /info
  heal:
    description: Heal Befehl
    usage: /heal
  broadcast:
    description: Bordcast Befehl
    usage: /broadcast
    aliases: ["br"]
